from enum import Enum
from pathlib import Path
import shutil

import pandas as pd

from hpc_performance_testing.config import load_yaml
from hpc_performance_testing.utils import validate_path, backup_existing_file
from hpc_performance_testing.logger import LoggerManager

# get logger
logger = LoggerManager.get_logger()

class CleanupScenario(str, Enum):
    RESUBMIT   = "resubmit"
    FINISHED   = "finished"
    DELETE_ALL = "delete_all"

class TestInstanceCleanup:

    TEST_YAML_NAME = "test_instance.yaml"
    ERR_LOG_NAME   = "runtime_err.log"
    
    def __init__(self):
        self.test_instance_path = self._get_test_instance_path()

    def _get_test_instance_path(self):
        test_yaml_path = Path(self.TEST_YAML_NAME)
        if not test_yaml_path.exists():
            return None
       
        try:
            cfg = load_yaml(test_yaml_path)
        except Exception:
            return None
        
        raw = cfg.get("runtime", {}).get("test_instance")
        if not raw:
            return None

        # Validate & normalize path; return None if invalid
        try:
            return validate_path(raw)
        except Exception:
            return None
        
    def _delete_test_yaml_log(self):
        test_yaml_file = Path(self.TEST_YAML_NAME)
        err_log_file = Path(self.ERR_LOG_NAME)
        
        for src in (test_yaml_file, err_log_file):
            src.unlink(missing_ok=True)
            logger.info(f"Delete file {src} if exists.")
        
        # check whether test_instance.yaml file is deleted
        return not test_yaml_file.exists()


    def _move_to(self) -> bool:
          
        dst = self.test_instance_path

        if dst is None or not dst.exists():
            return self._delete_test_yaml_log()
            
        test_yaml_file = Path(self.TEST_YAML_NAME)
        err_log_file = Path(self.ERR_LOG_NAME)
        
        for src in (test_yaml_file, err_log_file):
            if not src.exists():
                continue

            dst_file = dst/src.name
            if dst_file.exists():
                backup_existing_file(dst_file)
            shutil.move(str(src), str(dst))
            logger.info(f"Move file {src.name} to {str(dst)}")
        return not test_yaml_file.exists()
        
        
            
    def _merge_df(self):
        """merge the three parquets generated by testing framework"""
        root = self.test_instance_path
        if not root:
            logger.warning("Test instance is not found. Abort merging dfs.")
            return False
        
        results_dir = root / "results"
        
        src_files = [
        results_dir / "job_submission.parquet",  # df1 (anchor)
        results_dir / "job_exit_status.parquet", # df2
        results_dir / "job_output.parquet",      # df3
        ]

        missing = [p for p in src_files if not p.exists()]
        if missing:
            logger.warning("Missing result files: %s. Abort merging dfs.", ", ".join(str(p) for p in missing))
            return False
        
        try:
            df1, df2, df3 = [pd.read_parquet(p) for p in src_files]
            merged = df1.merge(df2, on="job_id", how="left")
            merged = merged.merge(df3, on="job_id", how="left")
            merged.to_parquet(results_dir/"job_summary.parquet", index=False)
        except Exception:
            logger.error("Fail to merge dfs and write out job summary parquet.", exc_info=True)
            return False
        
        # Remove sources only after successful write
        for p in src_files:
            p.unlink(missing_ok=True)

        return True
    
    def _remove_test_instance(self):
        root = self.test_instance_path
        if not root:
            logger.info("Test instance is not found. Abort remove_all action.")
            return False
        
        try:
            shutil.rmtree(root)
            logger.info(f"Removed test instance: {root}")
            return True
        except Exception:
            logger.error(f"Failed to remove test instance: {root}", exc_info=True)
            return False

    def apply(self, scenario: CleanupScenario | str) -> dict[str, bool]:
        # normalize to enum (raises ValueError on invalid internally)
        if not isinstance(scenario, CleanupScenario):
            scenario = CleanupScenario(scenario)

        results = {"clean_test_instance_yaml": False, "merge_df": False, "remove_all": False}

        if scenario is CleanupScenario.RESUBMIT:
            results["clean_test_instance_yaml"] = bool(self._move_to())
            return results

        if scenario is CleanupScenario.FINISHED:
            results["merge_df"] = bool(self._merge_df())
            results["clean_test_instance_yaml"] = bool(self._move_to())
            return results

        if scenario is CleanupScenario.DELETE_ALL:
            results["remove_all"] = bool(self._remove_test_instance())
            results["clean_test_instance_yaml"] = bool(self._move_to())
            return results

        return results

if __name__ == "__main__":
    cleanup = TestInstanceCleanup()
    res = cleanup.apply("delete_all")
    print(res)