from enum import Enum
from pathlib import Path
import shutil

import pandas as pd

from hpc_performance_testing.config import load_yaml
from hpc_performance_testing.utils import validate_path, backup_existing_file
from hpc_performance_testing.logger import LoggerManager

# get logger
logger = LoggerManager.get_logger()

class CleanupScenario(str, Enum):
    RESUBMIT   = "resubmit"
    FINISHED   = "finished"
    DELETE_ALL = "delete_all"

class TestInstanceCleanup:

    TEST_YAML_NAME = "test_instance.yaml"
    ERR_LOG_NAME   = "runtime_err.log"
    
    def __init__(self):
        self.test_instance_path = self._get_test_instance_path()

    def _get_test_instance_path(self):
        test_yaml_path = Path(self.TEST_YAML_NAME)
        if not test_yaml_path.exists():
            return None
       
        try:
            cfg = load_yaml(test_yaml_path)
        except Exception:
            return None
        
        raw = cfg.get("runtime", {}).get("test_instance")
        if not raw:
            return None

        # Validate & normalize path; return None if invalid
        try:
            return validate_path(raw)
        except Exception:
            return None

    def _move_to(self) -> list[str]:
        
        moved = []
        names = (self.TEST_YAML_NAME, self.ERR_LOG_NAME)
        sources = list(map(Path, names))    
        dst = self.test_instance_path

        if dst is None:
            for src in sources:
                src.unlink(missing_ok=True)
                logger.info(f"Test Instance is not found. Delete file {src.name} if exists.")
            return moved
        
        for src in sources:
            if not src.exists():
                continue

            dst_file = dst/src.name
            if dst_file.exists():
                backup_existing_file(dst_file)
            shutil.move(str(src), str(dst))
            logger.info(f"Move file {src.name} to {str(dst)}")
            moved.append(src.name)

        return moved
            
    def _merge_df(self):
        """merge the three parquets generated by testing framework"""
        if not self.test_instance_path:
            logger.warning("Test instance is not found. Abort merging dfs.")
            return False
        
        results_dir = Path(self.test_instance_path) / "results"
        
        src_files = [
        results_dir / "job_submission.parquet",  # df1 (anchor)
        results_dir / "job_exit_status.parquet", # df2
        results_dir / "job_output.parquet",      # df3
        ]

        missing = [p for p in src_files if not p.exists()]
        if missing:
            logger.warning("Missing result files: %s. Abort merging dfs.", ", ".join(str(p) for p in missing))
            return False
        
        try:
            df1, df2, df3 = [pd.read_parquet(p) for p in src_files]
            merged = df1.merge(df2, on="job_id", how="left")
            merged = merged.merge(df3, on="job_id", how="left")
            merged.to_parquet(results_dir/"job_summary.parquet", index=False)
        except Exception:
            logger.error("Fail to merge dfs and write out job summary parquet.", exc_info=True)
            return False
        
        # Remove sources only after successful write
        for p in src_files:
            p.unlink(missing_ok=True)

        return True


if __name__ == "__main__":
    cleanup = TestInstanceCleanup()
    cleanup._merge_df()